# -*- coding: utf-8 -*-
"""bookProgram_with_sqlite_db

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ykiKdarvf7IDpy44VnmT7wiUN7LrvDmx
"""

import sqlite3

# Create eBookstore Database
db = sqlite3.connect('ebookshop_db')
cursor = db.cursor()

# Create EBookstore Table
cursor.execute('''
  CREATE TABLE ebookstore(
    id INT PRIMARY KEY,
    Title VARCHAR(150),
    Author VARCHAR(150),
    Qty INT
  )''')

db.commit()

# Inserting Existing Data
book1 = 'A Tale of Two Cities'
author1 = 'Charles Dickens'
qty1 = 30

book2 = 'Harry Potter and the Philosopher\'s Stone'
author2 = 'J.K Rowling'
qty2 = 40

book3 = 'The Lion, the Witch and the Wardrobe'
author3 = 'C.S Lewis'
qty3 = 25

book4 = 'The Lord of the Rings'
author4 = 'J.R.R Tolkien'
qty4 = 37

book5 = 'Alice in Wonderland'
author5 = 'Lewis Carroll'
qty5 = 12

# Inserting the Existing Data into the Database
existing_book_data_ = [(book1,author1,qty1),
                      (book2,author2,qty2),
                      (book3,author3,qty3),
                      (book4,author4,qty4),
                      (book5,author5,qty5)]

cursor.executemany('''
INSERT INTO ebookstore(Title, Author, Qty)
VALUES(?,?,?)''', existing_book_data_)

'''The program should present the user with the following menu:
    1. Enter book
    2. Update book
    3. Delete book
    4. Search books
    0. Exit '''

# Book Database Program

bookOption = int(input("Please select the option applicable \
to your chosen method of delivery\
\n1. Enter book\
\n2. Update book\
\n3. Delete book\
\n4. Search books\
\nOption selected:  "))

if(bookOption == 1):
  book_name = input('Enter the name of the book: ')
  book_author = input('Enter the author of the book: ')
  book_qty = int(input('Enter the quantity of books: '))
  book_data = [(book_name, book_author, book_qty)]

  # Entering Data into the Database
  for books_data in book_data:
    cursor.executemany('''
    INSERT INTO ebookstore(Title, Author, Qty)
    VALUES(?,?,?)''', books_data)

    print('Book has been entered into the database')
    db.commit()

elif (bookOption == 2):
  update_book_title = input('Update the Book Title Information: ')
  update_book_author = input('Update the Book Author Information: ')
  update_books_qty = int(input('Update the Book Quantity: '))
  update_books = [(update_book_title, update_book_author, update_books_qty)]

  # Update Information in the Database
  for update_book in update_books:
    cursor.execute('''
    UPDATE ebookstore 
    SET Title = ? 
    WHERE Author = ? AND Qty = ?''',(update_book))

    print('The book information has been updated')
    db.commit()

elif (bookOption == 3):
  book_delete_option = input('Enter the title of the book you want to remove: ')

  # Delete Data off the Database
  cursor.execute('''
  DELETE FROM ebookstore 
  WHERE Title = ?''',(book_delete_option))

  print('Book has been deleted')
  db.commit()

elif (bookOption == 4):
  book_search = input('Enter the name of the book you want to search; ')
  author_search = input('Enter the name of the author you want to search; ')

  # Search for Data into the Database
  cursor.execute('''
  SELECT Title, Author 
  FROM ebookstore 
  WHERE Title=? OR Author=? ''', (book_search,author_search))

  print('Search has been completed')
  db.commit()

else:
  print('Wrong Information Selected!! - Please run the program again')

